REDSHIFT_USER = "k_shiraishi"
REDSHIFT_PASSWORD = "Eb{T~Dbk+;cZV(,G1xec"
REDSHIFT_HOST = "cronus-dwh1.ceai7ez3fflp.ap-northeast-1.redshift.amazonaws.com"
REDSHIFT_PORT = "5439"
REDSHIFT_DB = "da"
REDSHIFT_SCHEMA = "usedcar_dwh"
GOOGLE_API_KEY = "AIzaSyAeLDdZnjY_JTcv9vgZFHJcqbZ8wMpv6tk"


ENVIRONMENT=production
DEBUG=false
LOG_LEVEL=WARNING
